In [1]:
!pip install transformers

In [2]:
!pip install datasets

In [31]:
!pip install SentenceTransformer

ERROR: Could not find a version that satisfies the requirement SentenceTransformer (from versions: none)
ERROR: No matching distribution found for SentenceTransformer


In [3]:
from datasets import Dataset

In [4]:
!pip install sentence-transformers --prograss-bar off


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --prograss-bar


In [5]:
!pip install -U sentence-transformers

In [6]:
sentence_1 = "#Bitcoin is up 34% since Bank of England Governor said Be prepared to lose all your money in BTC and crypto."
sentence_2 =  "One of the biggest bull traps I've ever seen"

In [7]:
!pip install -Uqqq pip --progress-bar off

In [8]:
from sentence_transformers import SentenceTransformer, util

In [9]:
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [10]:
model.max_seq_length

384

In [11]:
corpus = [
"#Bitcoin is up 34% since Bank of England Governor said 'Be prepared to lose all your money in BTC and crypto.'", "One of the biggest bull traps I've ever seen",
"How I sleep knowing ethereum is going to 10k in 2023",
"Bitcoin is a scam",
"IS THE SBTC BOTTOM IN? Are you team BULL or team BEAR? Do you have the DATA to prove your point??",
"I will stop bragging about calling the top when I start bragging about calling the bottom. #bitcoin",
"First powerlifting meet of the year and a new squat PR!!",
"On January 9th, 2023, the American Academy of Pediatrics published new guidelines treating obesity in children and adolescents",
"What's worse, someone dropping the bar from the top of a deadlift or not putting their shopping cart away?",
" The sport of powerlifting includes squat bench and deadlift. But the concept of powerlifting is Force Mass x Acceleration."
]

In [12]:
corpus_embeddings = model.encode(corpus,show_progress_bar=True,convert_to_tensor=True)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [13]:
corpus_embeddings.shape

torch.Size([10, 768])

In [14]:
query = "how high will be bitcoin"

In [15]:
query_embedding = model.encode(query,convert_to_tensor=True)

In [16]:
query_embedding

tensor([-3.3793e-02,  1.6598e-02, -4.1849e-02,  4.8671e-03,  4.0209e-02,
        -1.9571e-02, -4.5454e-02, -1.2986e-02,  4.1175e-02, -4.7348e-03,
         5.1154e-03,  2.9511e-05, -3.3897e-02,  1.2314e-01, -2.5477e-03,
        -5.5161e-02,  3.3595e-02, -2.5237e-03,  9.9003e-04, -3.3011e-02,
        -3.3135e-03, -4.9212e-02,  3.4813e-02, -1.2339e-02, -2.2351e-02,
        -1.5709e-03,  3.0748e-02,  2.3593e-02, -4.3517e-02, -9.2837e-03,
        -5.0237e-02, -1.9132e-02, -5.5968e-02,  1.3551e-02,  1.4722e-06,
        -3.3751e-02,  7.6347e-03,  4.1565e-02, -2.4727e-02, -8.2647e-02,
        -8.6560e-02, -2.3749e-02, -4.7258e-03,  1.4648e-02, -3.4390e-02,
         3.8897e-02, -5.1706e-02,  2.5782e-02, -1.7911e-02,  2.6679e-02,
         1.9802e-03, -5.6009e-02,  5.6549e-02,  1.8522e-02,  8.1222e-03,
        -2.5320e-02,  1.7575e-02,  5.7294e-02, -1.5192e-02,  4.1968e-02,
         5.5158e-03,  1.7219e-02,  2.0678e-02,  5.8989e-04,  6.6354e-03,
         3.1803e-02,  2.4317e-02,  2.9280e-02, -2.7

In [17]:
util.cos_sim(query_embedding,corpus_embeddings[0])

tensor([[0.4826]])

In [18]:
sentence1_embedding = model.encode(sentence_1,convert_to_tensor=True)
sentence2_embedding = model.encode(sentence_2,convert_to_tensor=True)

In [19]:
util.cos_sim(sentence1_embedding,sentence2_embedding)

tensor([[0.1334]])

In [20]:
result = util.semantic_search(query_embedding,corpus_embeddings)[0]
result

[{'corpus_id': 2, 'score': 0.5038397312164307},
 {'corpus_id': 0, 'score': 0.4826172888278961},
 {'corpus_id': 5, 'score': 0.4214966297149658},
 {'corpus_id': 3, 'score': 0.4038848876953125},
 {'corpus_id': 4, 'score': 0.2667643129825592},
 {'corpus_id': 1, 'score': 0.08946854621171951},
 {'corpus_id': 6, 'score': 0.07887786626815796},
 {'corpus_id': 7, 'score': 0.054768506437540054},
 {'corpus_id': 8, 'score': -0.002571491291746497},
 {'corpus_id': 9, 'score': -0.0056485822424292564}]

In [21]:
for item in result:
  print(round(item["score"],2), corpus[item["corpus_id"]])

0.5 How I sleep knowing ethereum is going to 10k in 2023
0.48 #Bitcoin is up 34% since Bank of England Governor said 'Be prepared to lose all your money in BTC and crypto.'
0.42 I will stop bragging about calling the top when I start bragging about calling the bottom. #bitcoin
0.4 Bitcoin is a scam
0.27 IS THE SBTC BOTTOM IN? Are you team BULL or team BEAR? Do you have the DATA to prove your point??
0.09 One of the biggest bull traps I've ever seen
0.08 First powerlifting meet of the year and a new squat PR!!
0.05 On January 9th, 2023, the American Academy of Pediatrics published new guidelines treating obesity in children and adolescents
-0.0 What's worse, someone dropping the bar from the top of a deadlift or not putting their shopping cart away?
-0.01  The sport of powerlifting includes squat bench and deadlift. But the concept of powerlifting is Force Mass x Acceleration.


In [22]:
from sentence_transformers import  SentencesDataset, InputExample,losses
from torch.utils.data import DataLoader

In [23]:
dataset = SentencesDataset([
    InputExample(
        texts = [
            "#Bitcoin is up 34% since Bank of England Governor said Be prepared to lose all your money in BTC and crypto.",
            "One of the biggest bull traps I've ever seen"
        ],label =0.9
    )
], model)

In [24]:
dataloader = DataLoader(dataset,shuffle=True)
loss = losses.CosineSimilarityLoss(model=model)

In [25]:
save_path = 'trained_model'

In [26]:
model.fit(train_objectives=[(dataloader,loss)],epochs=10,warmup_steps=10,output_path=save_path)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

In [32]:
trained_model = SentenceTransformer(save_path)

In [34]:
sentence1_embedding = trained_model.encode(sentence_1,convert_to_tensor=True)
sentence2_embedding = trained_model.encode(sentence_2,convert_to_tensor=True)

In [35]:
util.cos_sim(sentence1_embedding,sentence2_embedding)

tensor([[0.8053]])